### ISSUE TITLE
Modular extensions

### ISSUE THREAD

**Issue by ludwig-max** [jakob-r/hugo-course#1]
It would be great, if including a new Chapter would be rather efficient. E.g.: We have 20 Chapters and I want to add a Chapter 3, which means moving all subsequent Chapters one place further. Thx :)

**Comment by jakob-r** [comment]
Can you elaborate what is the goal? It's annoying to have to rename all subsequent chapters? To my knowledge hugo is not really flexible in the folder structure :(

**Comment by ludwigbothmann** [comment]
Yes, that is exactly the point. But if that's not possible, then at least our hiwis don't get bore-out

**Comment by jakob-r** [comment]
A talented hiwi will write a script :)
