### ISSUE TITLE
Enable tex on entire website

### ISSUE THREAD

**Issue by lisa-wm** [jakob-r/hugo-course#13]
Tex can be used within quizdown environments enclosed in single dollar signs. The same does not work on the remaining page; enabling mathjax and using double dollar signs as required by mathjax, however, leads the quizzes to crash.

**Comment by jakob-r** [comment]
Partly solved here: https://github.com/jakob-r/courseTheme/commit/7a8097fac3664aefed12259bf283a910ab5278db

Please note: 
> If you want to use mathjax in quizdown you have to set `mathjax: false` in YAML header and you cannot use mathjax in other parts of the document :(

**Comment by jakob-r** [comment]
Should be completely solved with: https://github.com/jakob-r/courseTheme/commit/83398a2fa9c8154c6e6a3259eb05f14b02fc3b1d
