### ISSUE TITLE
change order of appearance for chapters in `home` view

### ISSUE THREAD

**Issue by lisa-wm** [jakob-r/hugo-course#14]
chapters appear in order of title set in .md files, meaning 1.10 will appear before 1.9 - is it possible to instead set order according to .md file names? or must titles be changed to 01-09 etc.? @jakob-r

**Comment by jakob-r** [comment]
Sorting should follow the filenames - there leading 01-09 is necessary. The displayed titles should not matter. It seems to work here: https://compstat-lmu.github.io/lecture_i2ml_2/chapters/11_advriskmin/ ? Where is it broken?

**Comment by lisa-wm** [comment]
No, I mean [here](https://compstat-lmu.github.io/lecture_i2ml_2/) in the `home` overview boxes, there they seem to be ordered according to titles

**Comment by jakob-r** [comment]
Ah thanks :sweat_smile: . Will fix it soon :)

**Comment by lisa-wm** [comment]
Thx!! 🙏🏻

**Comment by lisa-wm** [comment]
I just realized this also affects the forward and backward buttons in the subchapters - e.g., on the landing page of 16.1, there is a backward button leading to 16.10

**Comment by jakob-r** [comment]
fixed here https://github.com/slds-lmu/courseTheme/commit/e1512533e9bceb9cc9791eb12919541206ee89e9
