### ISSUE TITLE
remove titles from forward/backward buttons

### ISSUE THREAD

**Issue by lisa-wm** [jakob-r/hugo-course#15]
@jakob-r: the buttons overlap when the chapter titles are long - we would prefer to have only the chapter numbers appear. Also, as mentioned in issue [14](https://github.com/jakob-r/hugo-course/issues/14), the buttons are affected by the numbering problem when # chapter reaches double digits. Thanks!

**Comment by jakob-r** [comment]
Sorting is now solved using weights: 
- https://github.com/slds-lmu/courseTheme/commit/e6fd1cadc191b9e7483201e94aa8dbb4dc4a7935
- https://github.com/slds-lmu/i2ml/commit/fad9b0920be345329c1d3dd31766df61c32cb06a
- https://github.com/slds-lmu/i2ml/commit/c232bbb671d297705ff45a8a6ccc538719d45079
