### ISSUE TITLE
create exercise section

### ISSUE THREAD

**Issue by lisa-wm** [jakob-r/hugo-course#16]
@jakob-r, I just started to add an exercise section and realized that this is probably sth that should go directly into the theme, right? (if not, I'll do it myself)
* "Exercises" should appear at the top between "Chapters" and "Appendix"
* In the `home` section, "Exercises" should appear before "Cheat Sheets". If possible, could file URLs be listed in the box as with the chapters?
* The landing page should look as for cheat sheets (i.e., just a single .md to list the PDFs)
Merci 🙏🏻

**Comment by jakob-r** [comment]
is solved
